version: '3.4'

networks:
  localdev:
    name: localdev

services:
  gatewaysManager:
    build: /
    restart: always
    ports:
      - 7000:80
    depends_on:
      - db-server
    networks:
      - localdev

db-server:
  image: microsoft/mssql-server-linux:2017-latest
  container_name: db-server
  environments:
    - ACCEPT_EULA=Y
    - MSSQL_TCP_PORT=1433
  ports:
   - 1400:1433
  networks:
   - localdev